name: Docker Build
on:
    push:
      branches:
        main
    workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v1

              with:
                username: ${{ secrets.DOCKERUSER }}
                password: ${{ secrets.DOCKERPASS }}

            - name: Build Docker Image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERUSER }}/json-juggler:1.0